version: "3.8"
services:
  spe_frontend:
    image: mudit219/spe_client
    restart: unless-stopped
#    env_file: ./.env
    ports:
      - "3000:3000"
    networks:
      spe_network:

networks:
  spe_network: