---
- name: Pull and run the frontend image
  hosts: localhost
  connection: local
  tasks:
    - name: Copy docker-compose file from folder to remote host
      copy:
        src: ../docker-compose.yml
        dest: ./client/
    - name: Pull images as specified in docker compose
      command: docker-compose -f ./client/docker-compose.yml pull
    - name: Running the containers using docker-compose
      command: docker-compose -f ./client/docker-compose.yml up -d  
